# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Chris O'Donnell
tagline:          'Software Engineer'
description:      'A web developer, history buff, somewhat avid reader. I also attend a few meetups. Lives in NYC'
url:              http://chriscpo.github.io
baseurl:          /

author:
  name:           "Chris O'Donnell"
  url:            http://chriscpo.github.io

plugins:

# Custom vars

github:
  repo:           https://github.com/chrisCPO
