# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Chris O'Donnell
tagline:          'Software Engineer'
description:      'A web developer, history buff, somewhat avid reader. I also attend a few meetups. Lives in the NYC'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           "Chris O'Donnell"
  url:            https://github.com/chrisCPO

plugins:

# Custom vars
version:          3.6.0

github:
  repo:           https://github.com/chrisCPO
